//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsCaptcha
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", ConfigurationName="WsCaptcha.GeracaoSomSoap")]
    public interface GeracaoSomSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraWavLetras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraWavLetrasResponse GeraWavLetras(WsCaptcha.GeraWavLetrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraWavLetras", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraWavLetrasResponse> GeraWavLetrasAsync(WsCaptcha.GeraWavLetrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptcha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaResponse GeraComponentesCaptcha(WsCaptcha.GeraComponentesCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaResponse> GeraComponentesCaptchaAsync(WsCaptcha.GeraComponentesCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoWav" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaArquivoWavResponse GeraComponentesCaptchaArquivoWav(WsCaptcha.GeraComponentesCaptchaArquivoWavRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoWav" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoWavResponse> GeraComponentesCaptchaArquivoWavAsync(WsCaptcha.GeraComponentesCaptchaArquivoWavRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaDSResponse GeraComponentesCaptchaDS(WsCaptcha.GeraComponentesCaptchaDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaDS", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaDSResponse> GeraComponentesCaptchaDSAsync(WsCaptcha.GeraComponentesCaptchaDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoWav" +
            "eDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaArquivoWaveDSResponse GeraComponentesCaptchaArquivoWaveDS(WsCaptcha.GeraComponentesCaptchaArquivoWaveDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoWav" +
            "eDS", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoWaveDSResponse> GeraComponentesCaptchaArquivoWaveDSAsync(WsCaptcha.GeraComponentesCaptchaArquivoWaveDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/ValidaTextoCaptcha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.ValidaTextoCaptchaResponse ValidaTextoCaptcha(WsCaptcha.ValidaTextoCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/ValidaTextoCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.ValidaTextoCaptchaResponse> ValidaTextoCaptchaAsync(WsCaptcha.ValidaTextoCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoGer" +
            "al", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaArquivoGeralResponse GeraComponentesCaptchaArquivoGeral(WsCaptcha.GeraComponentesCaptchaArquivoGeralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaArquivoGer" +
            "al", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoGeralResponse> GeraComponentesCaptchaArquivoGeralAsync(WsCaptcha.GeraComponentesCaptchaArquivoGeralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaDSGeral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCaptcha.GeraComponentesCaptchaDSGeralResponse GeraComponentesCaptchaDSGeral(WsCaptcha.GeraComponentesCaptchaDSGeralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebFrameworkProdam/GeracaoSom/GeraComponentesCaptchaDSGeral", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaDSGeralResponse> GeraComponentesCaptchaDSGeralAsync(WsCaptcha.GeraComponentesCaptchaDSGeralRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraWavLetras", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraWavLetrasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrLetras;
        
        public GeraWavLetrasRequest()
        {
        }
        
        public GeraWavLetrasRequest(string pstrLetras)
        {
            this.pstrLetras = pstrLetras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraWavLetrasResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraWavLetrasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string GeraWavLetrasResult;
        
        public GeraWavLetrasResponse()
        {
        }
        
        public GeraWavLetrasResponse(string GeraWavLetrasResult)
        {
            this.GeraWavLetrasResult = GeraWavLetrasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptcha", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=5)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=6)]
        public string pstrUrlWaveGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=7)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=8)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaRequest()
        {
        }
        
        public GeraComponentesCaptchaRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping, byte[] pImagemValidacao, string pstrExtensaoArquivo, string pstrUrlWaveGerado, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pstrUrlWaveGerado = pstrUrlWaveGerado;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public string pstrUrlWaveGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaResponse()
        {
        }
        
        public GeraComponentesCaptchaResponse(byte[] pImagemValidacao, string pstrExtensaoArquivo, string pstrUrlWaveGerado, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pstrUrlWaveGerado = pstrUrlWaveGerado;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoWav", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoWavRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=5)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pWaveGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=7)]
        public string pstrNomeArquivoWaveSugerido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=8)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=9)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaArquivoWavRequest()
        {
        }
        
        public GeraComponentesCaptchaArquivoWavRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping, byte[] pImagemValidacao, string pstrExtensaoArquivo, byte[] pWaveGerado, string pstrNomeArquivoWaveSugerido, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pWaveGerado = pWaveGerado;
            this.pstrNomeArquivoWaveSugerido = pstrNomeArquivoWaveSugerido;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoWavResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoWavResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pWaveGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public string pstrNomeArquivoWaveSugerido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=5)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaArquivoWavResponse()
        {
        }
        
        public GeraComponentesCaptchaArquivoWavResponse(byte[] pImagemValidacao, string pstrExtensaoArquivo, byte[] pWaveGerado, string pstrNomeArquivoWaveSugerido, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pWaveGerado = pWaveGerado;
            this.pstrNomeArquivoWaveSugerido = pstrNomeArquivoWaveSugerido;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaDS", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaDSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        public GeraComponentesCaptchaDSRequest()
        {
        }
        
        public GeraComponentesCaptchaDSRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaDSResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaDSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public WsCaptcha.ArrayOfXElement GeraComponentesCaptchaDSResult;
        
        public GeraComponentesCaptchaDSResponse()
        {
        }
        
        public GeraComponentesCaptchaDSResponse(WsCaptcha.ArrayOfXElement GeraComponentesCaptchaDSResult)
        {
            this.GeraComponentesCaptchaDSResult = GeraComponentesCaptchaDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoWaveDS", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoWaveDSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        public GeraComponentesCaptchaArquivoWaveDSRequest()
        {
        }
        
        public GeraComponentesCaptchaArquivoWaveDSRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoWaveDSResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoWaveDSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public WsCaptcha.ArrayOfXElement GeraComponentesCaptchaArquivoWaveDSResult;
        
        public GeraComponentesCaptchaArquivoWaveDSResponse()
        {
        }
        
        public GeraComponentesCaptchaArquivoWaveDSResponse(WsCaptcha.ArrayOfXElement GeraComponentesCaptchaArquivoWaveDSResult)
        {
            this.GeraComponentesCaptchaArquivoWaveDSResult = GeraComponentesCaptchaArquivoWaveDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaTextoCaptcha", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class ValidaTextoCaptchaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrTextoDigitado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pRetornoValidacao;
        
        public ValidaTextoCaptchaRequest()
        {
        }
        
        public ValidaTextoCaptchaRequest(string pstrTextoDigitado, string pRetornoValidacao)
        {
            this.pstrTextoDigitado = pstrTextoDigitado;
            this.pRetornoValidacao = pRetornoValidacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaTextoCaptchaResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class ValidaTextoCaptchaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public bool ValidaTextoCaptchaResult;
        
        public ValidaTextoCaptchaResponse()
        {
        }
        
        public ValidaTextoCaptchaResponse(bool ValidaTextoCaptchaResult)
        {
            this.ValidaTextoCaptchaResult = ValidaTextoCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoGeral", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoGeralRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        public string pstrTipoArquivoSom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=6)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pSomGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=8)]
        public string pstrNomeArquivoSugerido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=9)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=10)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaArquivoGeralRequest()
        {
        }
        
        public GeraComponentesCaptchaArquivoGeralRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping, string pstrTipoArquivoSom, byte[] pImagemValidacao, string pstrExtensaoArquivo, byte[] pSomGerado, string pstrNomeArquivoSugerido, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
            this.pstrTipoArquivoSom = pstrTipoArquivoSom;
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pSomGerado = pSomGerado;
            this.pstrNomeArquivoSugerido = pstrNomeArquivoSugerido;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaArquivoGeralResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaArquivoGeralResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pImagemValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrExtensaoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pSomGerado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public string pstrNomeArquivoSugerido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        public string pRetornoValidacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=5)]
        public string pstrMensagemRetorno;
        
        public GeraComponentesCaptchaArquivoGeralResponse()
        {
        }
        
        public GeraComponentesCaptchaArquivoGeralResponse(byte[] pImagemValidacao, string pstrExtensaoArquivo, byte[] pSomGerado, string pstrNomeArquivoSugerido, string pRetornoValidacao, string pstrMensagemRetorno)
        {
            this.pImagemValidacao = pImagemValidacao;
            this.pstrExtensaoArquivo = pstrExtensaoArquivo;
            this.pSomGerado = pSomGerado;
            this.pstrNomeArquivoSugerido = pstrNomeArquivoSugerido;
            this.pRetornoValidacao = pRetornoValidacao;
            this.pstrMensagemRetorno = pstrMensagemRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaDSGeral", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaDSGeralRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public string pstrCaptchaChars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=1)]
        public string pstrCaptchaFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=2)]
        public int pstrCaptchaLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=3)]
        public int pstrCaptchaFontWarping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=4)]
        public string pstrTipoArquivoSom;
        
        public GeraComponentesCaptchaDSGeralRequest()
        {
        }
        
        public GeraComponentesCaptchaDSGeralRequest(string pstrCaptchaChars, string pstrCaptchaFont, int pstrCaptchaLength, int pstrCaptchaFontWarping, string pstrTipoArquivoSom)
        {
            this.pstrCaptchaChars = pstrCaptchaChars;
            this.pstrCaptchaFont = pstrCaptchaFont;
            this.pstrCaptchaLength = pstrCaptchaLength;
            this.pstrCaptchaFontWarping = pstrCaptchaFontWarping;
            this.pstrTipoArquivoSom = pstrTipoArquivoSom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeraComponentesCaptchaDSGeralResponse", WrapperNamespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", IsWrapped=true)]
    public partial class GeraComponentesCaptchaDSGeralResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WebFrameworkProdam/GeracaoSom", Order=0)]
        public WsCaptcha.ArrayOfXElement GeraComponentesCaptchaDSGeralResult;
        
        public GeraComponentesCaptchaDSGeralResponse()
        {
        }
        
        public GeraComponentesCaptchaDSGeralResponse(WsCaptcha.ArrayOfXElement GeraComponentesCaptchaDSGeralResult)
        {
            this.GeraComponentesCaptchaDSGeralResult = GeraComponentesCaptchaDSGeralResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GeracaoSomSoapChannel : WsCaptcha.GeracaoSomSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GeracaoSomSoapClient : System.ServiceModel.ClientBase<WsCaptcha.GeracaoSomSoap>, WsCaptcha.GeracaoSomSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GeracaoSomSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GeracaoSomSoapClient.GetBindingForEndpoint(endpointConfiguration), GeracaoSomSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeracaoSomSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GeracaoSomSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeracaoSomSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GeracaoSomSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeracaoSomSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WsCaptcha.GeraWavLetrasResponse GeraWavLetras(WsCaptcha.GeraWavLetrasRequest request)
        {
            return base.Channel.GeraWavLetras(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraWavLetrasResponse> GeraWavLetrasAsync(WsCaptcha.GeraWavLetrasRequest request)
        {
            return base.Channel.GeraWavLetrasAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaResponse GeraComponentesCaptcha(WsCaptcha.GeraComponentesCaptchaRequest request)
        {
            return base.Channel.GeraComponentesCaptcha(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaResponse> GeraComponentesCaptchaAsync(WsCaptcha.GeraComponentesCaptchaRequest request)
        {
            return base.Channel.GeraComponentesCaptchaAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaArquivoWavResponse GeraComponentesCaptchaArquivoWav(WsCaptcha.GeraComponentesCaptchaArquivoWavRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoWav(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoWavResponse> GeraComponentesCaptchaArquivoWavAsync(WsCaptcha.GeraComponentesCaptchaArquivoWavRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoWavAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaDSResponse GeraComponentesCaptchaDS(WsCaptcha.GeraComponentesCaptchaDSRequest request)
        {
            return base.Channel.GeraComponentesCaptchaDS(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaDSResponse> GeraComponentesCaptchaDSAsync(WsCaptcha.GeraComponentesCaptchaDSRequest request)
        {
            return base.Channel.GeraComponentesCaptchaDSAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaArquivoWaveDSResponse GeraComponentesCaptchaArquivoWaveDS(WsCaptcha.GeraComponentesCaptchaArquivoWaveDSRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoWaveDS(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoWaveDSResponse> GeraComponentesCaptchaArquivoWaveDSAsync(WsCaptcha.GeraComponentesCaptchaArquivoWaveDSRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoWaveDSAsync(request);
        }
        
        public WsCaptcha.ValidaTextoCaptchaResponse ValidaTextoCaptcha(WsCaptcha.ValidaTextoCaptchaRequest request)
        {
            return base.Channel.ValidaTextoCaptcha(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.ValidaTextoCaptchaResponse> ValidaTextoCaptchaAsync(WsCaptcha.ValidaTextoCaptchaRequest request)
        {
            return base.Channel.ValidaTextoCaptchaAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaArquivoGeralResponse GeraComponentesCaptchaArquivoGeral(WsCaptcha.GeraComponentesCaptchaArquivoGeralRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoGeral(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaArquivoGeralResponse> GeraComponentesCaptchaArquivoGeralAsync(WsCaptcha.GeraComponentesCaptchaArquivoGeralRequest request)
        {
            return base.Channel.GeraComponentesCaptchaArquivoGeralAsync(request);
        }
        
        public WsCaptcha.GeraComponentesCaptchaDSGeralResponse GeraComponentesCaptchaDSGeral(WsCaptcha.GeraComponentesCaptchaDSGeralRequest request)
        {
            return base.Channel.GeraComponentesCaptchaDSGeral(request);
        }
        
        public System.Threading.Tasks.Task<WsCaptcha.GeraComponentesCaptchaDSGeralResponse> GeraComponentesCaptchaDSGeralAsync(WsCaptcha.GeraComponentesCaptchaDSGeralRequest request)
        {
            return base.Channel.GeraComponentesCaptchaDSGeralAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeracaoSomSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GeracaoSomSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeracaoSomSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webdesenv5.prodam/pp9038_captcha/geracaosom.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GeracaoSomSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webdesenv5.prodam/pp9038_captcha/geracaosom.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GeracaoSomSoap,
            
            GeracaoSomSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
