// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class Aluno
    {
        public Aluno()
        {
            DispositivoComunicacaoAluno = new HashSet<DispositivoComunicacaoAluno>();
            ResponsavelAluno = new HashSet<ResponsavelAluno>();
            ResponsavelGeralAluno = new HashSet<ResponsavelGeralAluno>();
            SolicitacaoMatricula = new HashSet<SolicitacaoMatricula>();
        }

        public int CdAluno { get; set; }
        public string NmAluno { get; set; }
        public DateTime DtNascimentoAluno { get; set; }
        public string CdSexoAluno { get; set; }
        public string NmMaeAluno { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdOperador { get; set; }
        public int? TpRacaCor { get; set; }
        public int? CdOrgaoEmissor { get; set; }
        public int? CdPaisMec { get; set; }
        public string SgUfRgAluno { get; set; }
        public DateTime? DtEntradaPais { get; set; }
        public int? CdDistritoCartorioCertidao { get; set; }
        public long? CdCpfAluno { get; set; }
        public string NrRgAluno { get; set; }
        public string CdDigitoRgAluno { get; set; }
        public DateTime? DtEmissaoRg { get; set; }
        public string CdIdentificacaoSocial { get; set; }
        public int? TpCertidaoAluno { get; set; }
        public string NrCertidaoAluno { get; set; }
        public string NrFolhaCertidaoAluno { get; set; }
        public string NrLivroCertidaoAluno { get; set; }
        public DateTime? DtEmissaoCertidao { get; set; }
        public string NrRegistroEstado { get; set; }
        public string CdDigitoRegistroEstado { get; set; }
        public DateTime? DtAtualizacaoRegistroEstado { get; set; }
        public string InMaeFalecida { get; set; }
        public string NmPaiAluno { get; set; }
        public string SgUfRegistroAlunoEstado { get; set; }
        public string InPaiFalecido { get; set; }
        public DateTime? DtInclusaoCadastro { get; set; }
        public int? CdMunicipioNascimento { get; set; }
        public int? CdMunicipioCertidao { get; set; }
        public decimal? CdInepAluno { get; set; }
        public string CdMatriculaCertidaoAluno { get; set; }
        public int? CdAlunoPrincipal { get; set; }
        public DateTime? DtFalecimentoAluno { get; set; }
        public string CdNacionalidadeAluno { get; set; }
        public string SgUfNascimentoAluno { get; set; }
        public string NrRneAluno { get; set; }
        public string InRgAlunoConfere { get; set; }
        public string InCertidaoAlunoConfere { get; set; }
        public string InRneAlunoConfere { get; set; }
        public string InDocumentoNacionalApresentado { get; set; }
        public string TxDocumentoNacionalNaoApresentado { get; set; }
        public int? CdCartorioCertidao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public string NmSocialAluno { get; set; }
        public int? CdTipoSigilo { get; set; }
        public string CdSexoMae { get; set; }
        public string CdNacionalidadeMae { get; set; }
        public int? CdPaisOrigemMae { get; set; }
        public string CdSexoPai { get; set; }
        public string CdNacionalidadePai { get; set; }
        public int? CdPaisOrigemPai { get; set; }
        public string InConstaPaiDocumento { get; set; }
        public string InCpfValidadoReceitaFederal { get; set; }
        public string InAutorizacaoGeracaoCpf { get; set; }

        public virtual ICollection<DispositivoComunicacaoAluno> DispositivoComunicacaoAluno { get; set; }
        public virtual ICollection<ResponsavelAluno> ResponsavelAluno { get; set; }
        public virtual ICollection<ResponsavelGeralAluno> ResponsavelGeralAluno { get; set; }
        public virtual ICollection<SolicitacaoMatricula> SolicitacaoMatricula { get; set; }
    }
}