// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class Aplicacao
    {
        public int CiSubsistema { get; set; }
        public int CiAplicacao { get; set; }
        public string NmAplicacao { get; set; }
        public string DcAplicacao { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdOperador { get; set; }
    }
}