// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class DispositivoComunicacaoAluno
    {
        public int CdDispositivoComunicacaoAluno { get; set; }
        public int CdAluno { get; set; }
        public int TpDispositivoComunicacao { get; set; }
        public int CdLocalDispositivoComunicacao { get; set; }
        public DateTime DtInicio { get; set; }
        public string DcDispositivo { get; set; }
        public string CdOperador { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdDdd { get; set; }
        public string CdRamal { get; set; }
        public string NmContato { get; set; }
        public DateTime? DtFim { get; set; }
        public string TpResponsavelDispositivoComunicacao { get; set; }
        public string InAutorizaEnvioSms { get; set; }
        public string TxRelacionamentoContato { get; set; }
        public int? CdTipoTurno { get; set; }

        public virtual Aluno CdAlunoNavigation { get; set; }
    }
}