// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class Endereco
    {
        public Endereco()
        {
            ResponsavelAlunoCdEnderecoComercialNavigation = new HashSet<ResponsavelAluno>();
            ResponsavelAlunoCiEnderecoNavigation = new HashSet<ResponsavelAluno>();
            ResponsavelGeralCdEnderecoComercialNavigation = new HashSet<ResponsavelGeral>();
            ResponsavelGeralCdEnderecoNavigation = new HashSet<ResponsavelGeral>();
            SolicitacaoMatriculaCdEnderecoBaseNavigation = new HashSet<SolicitacaoMatricula>();
            SolicitacaoMatriculaCdEnderecoOpcionalNavigation = new HashSet<SolicitacaoMatricula>();
        }

        public long CiEndereco { get; set; }
        public int TpLogradouro { get; set; }
        public string DcPontoReferencia { get; set; }
        public string SgTituloLogradouro { get; set; }
        public string NmLogradouro { get; set; }
        public string CdNrEndereco { get; set; }
        public string DcComplementoEndereco { get; set; }
        public string NmBairro { get; set; }
        public int? CdCep { get; set; }
        public int? CdLogradouro { get; set; }
        public int? CdMicroRegiao { get; set; }
        public long? CdSqlEndereco { get; set; }
        public string TpLocalizacaoEndereco { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdOperador { get; set; }
        public string CdCaixaPostal { get; set; }
        public int? CdDistritoMec { get; set; }
        public int? CdMunicipio { get; set; }
        public int? CdSubPrefeitura { get; set; }
        public decimal? CdCoordenadaGeoX { get; set; }
        public decimal? CdCoordenadaGeoY { get; set; }

        public virtual TipoLogradouro TpLogradouroNavigation { get; set; }
        public virtual ICollection<ResponsavelAluno> ResponsavelAlunoCdEnderecoComercialNavigation { get; set; }
        public virtual ICollection<ResponsavelAluno> ResponsavelAlunoCiEnderecoNavigation { get; set; }
        public virtual ICollection<ResponsavelGeral> ResponsavelGeralCdEnderecoComercialNavigation { get; set; }
        public virtual ICollection<ResponsavelGeral> ResponsavelGeralCdEnderecoNavigation { get; set; }
        public virtual ICollection<SolicitacaoMatricula> SolicitacaoMatriculaCdEnderecoBaseNavigation { get; set; }
        public virtual ICollection<SolicitacaoMatricula> SolicitacaoMatriculaCdEnderecoOpcionalNavigation { get; set; }
    }
}