// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class ResponsavelGeral
    {
        public ResponsavelGeral()
        {
            DispositivoComunicacaoResponsavel = new HashSet<DispositivoComunicacaoResponsavel>();
            ResponsavelCns = new HashSet<ResponsavelCns>();
            ResponsavelGeralAluno = new HashSet<ResponsavelGeralAluno>();
        }

        public int CdResponsavelGeral { get; set; }
        public decimal? CdCpfResponsavel { get; set; }
        public string InCpfResponsavelConferido { get; set; }
        public string NmResponsavel { get; set; }
        public long? CdEndereco { get; set; }
        public string NrRgResponsavel { get; set; }
        public string CdDigitoRgResponsavel { get; set; }
        public string SgUfRgResponsavel { get; set; }
        public string NmMaeResponsavel { get; set; }
        public DateTime? DtNascimentoMaeResponsavel { get; set; }
        public short? CdTipoDocumentoEstrangeiro { get; set; }
        public string NrDocumentoEstrangeiro { get; set; }
        public string CdSituacaoDocumentoResponsavel { get; set; }
        public string CdOperador { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public long? CdEnderecoComercial { get; set; }

        public virtual Endereco CdEnderecoComercialNavigation { get; set; }
        public virtual Endereco CdEnderecoNavigation { get; set; }
        public virtual TipoDocumentoEstrangeiro CdTipoDocumentoEstrangeiroNavigation { get; set; }
        public virtual ICollection<DispositivoComunicacaoResponsavel> DispositivoComunicacaoResponsavel { get; set; }
        public virtual ICollection<ResponsavelCns> ResponsavelCns { get; set; }
        public virtual ICollection<ResponsavelGeralAluno> ResponsavelGeralAluno { get; set; }
    }
}