// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class ResponsavelAluno
    {
        public int CdIdentificadorResponsavel { get; set; }
        public int? CdAluno { get; set; }
        public decimal? TpPessoaResponsavel { get; set; }
        public string NmResponsavel { get; set; }
        public long? CiEndereco { get; set; }
        public string NrRgResponsavel { get; set; }
        public string CdDigitoRgResponsavel { get; set; }
        public string SgUfRgResponsavel { get; set; }
        public decimal? CdCpfResponsavel { get; set; }
        public string CdDddCelularResponsavel { get; set; }
        public string NrCelularResponsavel { get; set; }
        public string CdDddTelefoneFixoResponsavel { get; set; }
        public string NrTelefoneFixoResponsavel { get; set; }
        public string CdSituacaoDocumentoResponsavel { get; set; }
        public DateTime DtInicio { get; set; }
        public DateTime? DtFim { get; set; }
        public string CdOperador { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdDddTelefoneComercialResponsavel { get; set; }
        public string NrTelefoneComercialResponsavel { get; set; }
        public string NrRamalTelefoneComercialResponsavel { get; set; }
        public string InCpfResponsavelConfere { get; set; }
        public string InAutorizaEnvioSms { get; set; }
        public string EmailResponsavel { get; set; }
        public int? CdTipoTurnoCelular { get; set; }
        public int? CdTipoTurnoComercial { get; set; }
        public int? CdTipoTurnoFixo { get; set; }
        public long? CdEnderecoComercial { get; set; }
        public string NmMaeResponsavel { get; set; }
        public DateTime? DtNascimentoMaeResponsavel { get; set; }
        public short? CdTipoDocumentoEstrangeiro { get; set; }
        public string NrDocumentoEstrangeiro { get; set; }
        public string InRegistroMigrado { get; set; }
        public int? CdResponsavelGeral { get; set; }
        public int? CdResponsavelGeralAluno { get; set; }
        public string TpSelecaoResponsavelAluno { get; set; }
        public string TpSelecaoMigracaoSme { get; set; }
        public DateTime? DtMigracao { get; set; }
        public string CdOperadorMigracao { get; set; }

        public virtual Aluno CdAlunoNavigation { get; set; }
        public virtual Endereco CdEnderecoComercialNavigation { get; set; }
        public virtual Endereco CiEnderecoNavigation { get; set; }
    }
}