// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class SolicitacaoMatricula
    {
        public SolicitacaoMatricula()
        {
            SolicitacaoMatriculaPreNatal = new HashSet<SolicitacaoMatriculaPreNatal>();
        }

        public int CdSolicitacaoMatricula { get; set; }
        public int CdAluno { get; set; }
        public string CdUnidadeEducacao { get; set; }
        public string TpOrigem { get; set; }
        public string StSolicitacao { get; set; }
        public DateTime DtStatusSolicitacao { get; set; }
        public string CdOperador { get; set; }
        public DateTime DtAtlzTab { get; set; }
        public int? CdMicroRegiao { get; set; }
        public int? CdModalidadeEnsino { get; set; }
        public int? CdEtapaEnsino { get; set; }
        public int? CdTipoPrograma { get; set; }
        public int? CdCicloEnsino { get; set; }
        public int? CdSerieEnsino { get; set; }
        public int? CdTipoMotivoRecusaMatricula { get; set; }
        public string DcObservacaoStatus { get; set; }
        public DateTime? DtProtocoloDesistenciaMatricula { get; set; }
        public short? AnLetivo { get; set; }
        public DateTime? DtInscricao { get; set; }
        public int? CdSerieEnsinoComposicao { get; set; }
        public long? CdEnderecoBase { get; set; }
        public int? CiTipoEnderecoBase { get; set; }
        public DateTime? DtEnderecoBase { get; set; }
        public DateTime? DtEnderecoOpcional { get; set; }
        public long? CdEnderecoOpcional { get; set; }

        public virtual Aluno CdAlunoNavigation { get; set; }
        public virtual Endereco CdEnderecoBaseNavigation { get; set; }
        public virtual Endereco CdEnderecoOpcionalNavigation { get; set; }
        public virtual ICollection<SolicitacaoMatriculaPreNatal> SolicitacaoMatriculaPreNatal { get; set; }
    }
}