// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class TipoLogradouro
    {
        public TipoLogradouro()
        {
            Endereco = new HashSet<Endereco>();
        }

        public int TpLogradouro { get; set; }
        public string DcTpLogradouro { get; set; }
        public decimal NrOrdemLogradouro { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }
        public string CdOperador { get; set; }
        public DateTime? DtCancelamento { get; set; }

        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}