// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProdamSP.Domain.Entities
{
    public partial class TipoPessoaResponsavel
    {
        public TipoPessoaResponsavel()
        {
            ResponsavelGeralAluno = new HashSet<ResponsavelGeralAluno>();
        }

        public int CdTipoPessoaResponsavel { get; set; }
        public string DcTipoPessoaResponsavel { get; set; }
        public string CdOperador { get; set; }
        public DateTime DtAtualizacaoTabela { get; set; }

        public virtual ICollection<ResponsavelGeralAluno> ResponsavelGeralAluno { get; set; }
    }
}