//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using WcfCoreMessageEncoder;

namespace PreNatalService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.prodam.sp.gov.br", ConfigurationName="PreNatalService.PreNatalServicePortType")]
    public interface PreNatalServicePortType
    {
        [System.ServiceModel.OperationContractAttribute(Action = "urn:pesquisar", ReplyAction = "urn:pesquisarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        PreNatalService.pesquisarResponse pesquisar(PreNatalService.pesquisarRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="urn:pesquisar", ReplyAction="urn:pesquisarResponse")]    
        System.Threading.Tasks.Task<PreNatalService.pesquisarResponse> pesquisarAsync(PreNatalService.pesquisarRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:ping", ReplyAction = "urn:pingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        PreNatalService.pingResponse ping(PreNatalService.pingRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="urn:ping", ReplyAction="urn:pingResponse")]      
        System.Threading.Tasks.Task<PreNatalService.pingResponse> pingAsync(PreNatalService.pingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.prodam.sp.gov.br/xsd")]
    public partial class DadosPreNatal
    {
        
        private string codRetornoField;
        
        private System.Nullable<System.DateTime> dataCadastroPreNatalField;
        
        private bool dataCadastroPreNatalFieldSpecified;
        
        private System.Nullable<System.DateTime> dataInterrupcaoField;
        
        private bool dataInterrupcaoFieldSpecified;
        
        private System.Nullable<System.DateTime> dataPartoField;
        
        private bool dataPartoFieldSpecified;
        
        private System.Nullable<System.DateTime> dataPrevisaoPartoField;
        
        private bool dataPrevisaoPartoFieldSpecified;
        
        private System.Nullable<System.DateTime> dataUltimaConsultaField;
        
        private bool dataUltimaConsultaFieldSpecified;
        
        private System.Nullable<System.DateTime> dataUltimaMenstruacaoField;
        
        private bool dataUltimaMenstruacaoFieldSpecified;
        
        private string msgRetornoField;
        
        private string numeroCnsField;
        
        private string numeroSisPreNatalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codRetorno
        {
            get
            {
                return this.codRetornoField;
            }
            set
            {
                this.codRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dataCadastroPreNatal
        {
            get
            {
                return this.dataCadastroPreNatalField;
            }
            set
            {
                this.dataCadastroPreNatalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataCadastroPreNatalSpecified
        {
            get
            {
                return this.dataCadastroPreNatalFieldSpecified;
            }
            set
            {
                this.dataCadastroPreNatalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> dataInterrupcao
        {
            get
            {
                return this.dataInterrupcaoField;
            }
            set
            {
                this.dataInterrupcaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInterrupcaoSpecified
        {
            get
            {
                return this.dataInterrupcaoFieldSpecified;
            }
            set
            {
                this.dataInterrupcaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dataParto
        {
            get
            {
                return this.dataPartoField;
            }
            set
            {
                this.dataPartoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPartoSpecified
        {
            get
            {
                return this.dataPartoFieldSpecified;
            }
            set
            {
                this.dataPartoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dataPrevisaoParto
        {
            get
            {
                return this.dataPrevisaoPartoField;
            }
            set
            {
                this.dataPrevisaoPartoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataPrevisaoPartoSpecified
        {
            get
            {
                return this.dataPrevisaoPartoFieldSpecified;
            }
            set
            {
                this.dataPrevisaoPartoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> dataUltimaConsulta
        {
            get
            {
                return this.dataUltimaConsultaField;
            }
            set
            {
                this.dataUltimaConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimaConsultaSpecified
        {
            get
            {
                return this.dataUltimaConsultaFieldSpecified;
            }
            set
            {
                this.dataUltimaConsultaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> dataUltimaMenstruacao
        {
            get
            {
                return this.dataUltimaMenstruacaoField;
            }
            set
            {
                this.dataUltimaMenstruacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimaMenstruacaoSpecified
        {
            get
            {
                return this.dataUltimaMenstruacaoFieldSpecified;
            }
            set
            {
                this.dataUltimaMenstruacaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string msgRetorno
        {
            get
            {
                return this.msgRetornoField;
            }
            set
            {
                this.msgRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string numeroCns
        {
            get
            {
                return this.numeroCnsField;
            }
            set
            {
                this.numeroCnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string numeroSisPreNatal
        {
            get
            {
                return this.numeroSisPreNatalField;
            }
            set
            {
                this.numeroSisPreNatalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pesquisar", WrapperNamespace="http://service.prodam.sp.gov.br", IsWrapped=true)]
    public partial class pesquisarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.prodam.sp.gov.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numCNS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.prodam.sp.gov.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numSisPreNatal;
        
        public pesquisarRequest()
        {
        }
        
        public pesquisarRequest(string numCNS, string numSisPreNatal)
        {
            this.numCNS = numCNS;
            this.numSisPreNatal = numSisPreNatal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pesquisarResponse", WrapperNamespace="http://service.prodam.sp.gov.br", IsWrapped=true)]
    public partial class pesquisarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.prodam.sp.gov.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PreNatalService.DadosPreNatal @return;
        
        public pesquisarResponse()
        {
        }
        
        public pesquisarResponse(PreNatalService.DadosPreNatal @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ping", WrapperNamespace="http://service.prodam.sp.gov.br", IsWrapped=true)]
    public partial class pingRequest
    {
        
        public pingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pingResponse", WrapperNamespace="http://service.prodam.sp.gov.br", IsWrapped=true)]
    public partial class pingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.prodam.sp.gov.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public pingResponse()
        {
        }
        
        public pingResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PreNatalServicePortTypeChannel : PreNatalService.PreNatalServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PreNatalServicePortTypeClient : System.ServiceModel.ClientBase<PreNatalService.PreNatalServicePortType>, PreNatalService.PreNatalServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PreNatalServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(PreNatalServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), PreNatalServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreNatalServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PreNatalServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreNatalServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PreNatalServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreNatalServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public PreNatalService.pesquisarResponse pesquisar(PreNatalService.pesquisarRequest request)
        {
            return base.Channel.pesquisar(request);
        }

        public System.Threading.Tasks.Task<PreNatalService.pesquisarResponse> pesquisarAsync(PreNatalService.pesquisarRequest request)
        {
            return base.Channel.pesquisarAsync(request);
        }

        public PreNatalService.pingResponse ping(PreNatalService.pingRequest request)
        {
            return base.Channel.ping(request);
        }

        public System.Threading.Tasks.Task<PreNatalService.pingResponse> pingAsync(PreNatalService.pingRequest request)
        {
            return base.Channel.pingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PreNatalServiceHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PreNatalServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();

                var encoding = new CustomTextMessageBindingElement();

                encoding.MediaType = "application/soap+xml";
                encoding.MediaTypeResponse = "multipart/related";
                encoding.ReaderQuotas.MaxStringContentLength = 2147483647;
                encoding.ReaderQuotas.MaxArrayLength = 2147483647;
                encoding.ReaderQuotas.MaxBytesPerRead = 2147483647;
                encoding.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);

                result.Elements.Add(encoding);

                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PreNatalServiceHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.64.117:8080/smsservices/services/PreNatalService.PreNatalServiceHttp" +
                        "Soap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.PreNatalServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.64.117:8080/smsservices/services/PreNatalService.PreNatalServiceHttp" +
                        "Soap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PreNatalServiceHttpSoap11Endpoint,
            
            PreNatalServiceHttpSoap12Endpoint,
        }
    }
}
